require 'afhbot/output-log'
require 'afhbot/parser-config'
require 'afhbot/command'
require 'afhbot/client-discord'
require 'afhbot/proto-tls'
require 'afhbot/proto-twitch'
require 'afhbot/client-twitch'
require 'afhbot/modules/discord-group'